// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_bil_hikmah/test/home/logic/home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bil_hikmah/feature/home/domain/model/adhan_schedule.dart'
    as _i2;
import 'package:flutter_bil_hikmah/feature/home/domain/repository/home_repository.dart'
    as _i3;
import 'package:flutter_bil_hikmah/feature/video_dakwah/repository/video_dakwah_models.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdhanSchedule_0 extends _i1.SmartFake implements _i2.AdhanSchedule {
  _FakeAdhanSchedule_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> onGetHomeData() => (super.noSuchMethod(
        Invocation.method(
          #onGetHomeData,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.AdhanSchedule> getAdhanSchedule(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdhanSchedule,
          [city],
        ),
        returnValue: _i4.Future<_i2.AdhanSchedule>.value(_FakeAdhanSchedule_0(
          this,
          Invocation.method(
            #getAdhanSchedule,
            [city],
          ),
        )),
      ) as _i4.Future<_i2.AdhanSchedule>);
  @override
  _i4.Future<List<_i5.VideoDakwahModels>> onGetVideoDakwah() =>
      (super.noSuchMethod(
        Invocation.method(
          #onGetVideoDakwah,
          [],
        ),
        returnValue: _i4.Future<List<_i5.VideoDakwahModels>>.value(
            <_i5.VideoDakwahModels>[]),
      ) as _i4.Future<List<_i5.VideoDakwahModels>>);
}
