// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_bil_hikmah/test/amalan_sunnah/logic/amalan_sunnah_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_bil_hikmah/feature/amalan_sunnah/repository/amalan_sunnah_item.dart'
    as _i4;
import 'package:flutter_bil_hikmah/feature/amalan_sunnah/repository/amalan_sunnah_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AmalanSunnahRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmalanSunnahRepository extends _i1.Mock
    implements _i2.AmalanSunnahRepository {
  MockAmalanSunnahRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AmalanSunnahItem>> getAllAmalanSunnah() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAmalanSunnah,
          [],
        ),
        returnValue: _i3.Future<List<_i4.AmalanSunnahItem>>.value(
            <_i4.AmalanSunnahItem>[]),
      ) as _i3.Future<List<_i4.AmalanSunnahItem>>);
}
