// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3njZ-ZrbL5Bz6sl1Y9wGjuX0_GOyGuN4',
    appId: '1:391048146526:web:521ddff93072a16c628ecf',
    messagingSenderId: '391048146526',
    projectId: 'bilhikmah-243fd',
    authDomain: 'bilhikmah-243fd.firebaseapp.com',
    storageBucket: 'bilhikmah-243fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb0roUaTxzAmbyMOKiRZR8kY8hdNNhQQ4',
    appId: '1:391048146526:android:529c0dc34738f742628ecf',
    messagingSenderId: '391048146526',
    projectId: 'bilhikmah-243fd',
    storageBucket: 'bilhikmah-243fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOVwWzb5Rc6mC_QwG7XSsQiy6X3BPI6o',
    appId: '1:391048146526:ios:da5e84b0488fd7cb628ecf',
    messagingSenderId: '391048146526',
    projectId: 'bilhikmah-243fd',
    storageBucket: 'bilhikmah-243fd.appspot.com',
    androidClientId: '391048146526-v8g4nr3tv7q6p9couu17kk1qgpke1fpo.apps.googleusercontent.com',
    iosClientId: '391048146526-jklscf79ep0i47n1brb04lf4qcte147f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBilHikmah',
  );
}
