// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_bil_hikmah/test/alquran/logic/quran_logic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bil_hikmah/feature/al_quran/domain/model/quran_item.dart'
    as _i5;
import 'package:flutter_bil_hikmah/feature/al_quran/domain/model/surah_item.dart'
    as _i2;
import 'package:flutter_bil_hikmah/feature/al_quran/domain/repository/quran_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSurahItem_0 extends _i1.SmartFake implements _i2.SurahItem {
  _FakeSurahItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuranRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuranRepository extends _i1.Mock implements _i3.QuranRepository {
  MockQuranRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.QuranItemData>> quranAll() => (super.noSuchMethod(
        Invocation.method(
          #quranAll,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.QuranItemData>>.value(<_i5.QuranItemData>[]),
      ) as _i4.Future<List<_i5.QuranItemData>>);
  @override
  _i4.Future<_i2.SurahItem> surahItem(int? surah) => (super.noSuchMethod(
        Invocation.method(
          #surahItem,
          [surah],
        ),
        returnValue: _i4.Future<_i2.SurahItem>.value(_FakeSurahItem_0(
          this,
          Invocation.method(
            #surahItem,
            [surah],
          ),
        )),
      ) as _i4.Future<_i2.SurahItem>);
}
