import "../../scripts/fastfile"

default_platform(:android)

platform :android do
  private_lane :build_apk do |options|
    unless options[:build_number]
      UI.user_error!("Please specify build number with the build_number parameter")
    end

    fetch_dependencies

    build_number = options[:build_number]

    sh_on_root(command: "flutter build apk --release --verbose --build-number=#{build_number+50}")
  end

  lane :deploy_to_firebase do |options|
    unless options[:app_id]
      UI.user_error!("Please specify firebase app id with the app_id parameter")
    end

    unless options[:firebase_cli_token]
      UI.user_error!("Please specify Firebase Token with the firebase_cli_token parameter")
    end

    # Generate APK File with given build_number
    build_apk(build_number: options[:build_number])

    # Prepare firebase distributions parameter
    artifact_type = "APK"
    artifact_path = "#{root_path}/build/app/outputs/flutter-apk/app-release.apk"
    groups = "internal-1"
    app_id = options[:app_id]
    firebase_cli_token = options[:firebase_cli_token]
    release_notes = options.fetch(:release_notes, "No Release Notes")

    # # Upload APK to firebase
    firebase_app_distribution(
      app: app_id,
      android_artifact_type: artifact_type,
      android_artifact_path: artifact_path,
      groups: groups,
      firebase_cli_token: firebase_cli_token,
      release_notes: release_notes,
    )
  end
end
