name: Deploy Android APK to Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: "The Release notes that will used for the apk file"
        required: false
env:
  github_runner: $GITHUB_RUN_NUMBER

jobs:
  deploy-android-apk-to-firebase:
    name: "Deploy Android APK to Firebase"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
          channel: "stable"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Create keystore file
        run: |
          cd android
          touch key.properties
          echo storePassword=${{ secrets.STORE_PASSWORD }} >> key.properties
          echo keyPassword=${{ secrets.KEY_PASSSWORD }} >> key.properties
          echo keyAlias=${{ secrets.KEY_ALIAS }} >> key.properties
          echo storeFile=../../android/bilhikmah-keystore.jks >> key.properties
          cat key.properties
          cd ..
      - name: Convert Env Variable to Int
        run: |
          # Use JavaScript to convert the string to an integer
          const stringValue = $GITHUB_RUN_NUMBER;
          const intValue = parseInt(stringValue) + 50;

          console.log(`Original string value: ${stringValue}`);
          console.log(`Converted integer value: ${intValue}`);

          # You can use the intValue in subsequent steps
          echo "::set-env name=GITHUB_RUNNER_PARSED::${intValue}"
      - name: Build APK and Deploy to firebase
        run: |
          cd android && bundle exec fastlane deploy_to_firebase app_id:${{ secrets.ANDROID_FIREBASE_APP_ID }} firebase_cli_token:${{ secrets.FIREBASE_CLI_TOKEN }} release_notes:"${{ github.event.inputs.release_notes }}" build_number:$GITHUB_RUNNER_PARSED && cd ..
