name: Deploy Android APK to Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: "The Release notes that will used for the apk file"
        required: false

jobs:
  deploy-android-apk-to-firebase:
    name: "Deploy Android APK to Firebase"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.1"
          channel: "stable"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Build APK and Deploy to firebase
        run: cd android && bundle exec fastlane deploy_to_firebase app_id:${{ secrets.ANDROID_FIREBASE_APP_ID }} firebase_cli_token:${{ secrets.FIREBASE_CLI_TOKEN }} release_notes:"${{ github.event.inputs.release_notes }}" && cd ..
