name: Self Hosted

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Runners'
        required: true
        default: 'local-diky'
        type: choice
        options:
          - local-diky
          - local-tama
          - local-fauzan
          - local-daewu
  push:
    branches:
      - self-hosted/diky-try-1

jobs:
  deploy-ios-ipa-to-firebase:
    name: "Deploy ios IPA to Firebase"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: set Up Xcode
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: "15.4"

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: "17"
      #     distribution: "adopt"

      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: "3.13.0"

      # - name: Install ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 3.0.6
      #     bundler-cache: true

      # - name: Install bundle cocoapods fastlane
      #   run: |
      #     cd ios && sudo gem install bundler && cd ..

      # - name: Install Fastlane
      #   run: cd ios && bundle install && cd ..

      - name: Convert Env Variable to Int
        run: |
          # Convert github runner number to int type
          GITHUB_RUNNER=$GITHUB_RUN_NUMBER
          GITHUB_RUNNER_CONVERTED=$((GITHUB_RUNNER))

          # Read the contents of the file into a variable - Version Name
          MAJOR_VERSION=2.72.

          echo "Original string value: ${GITHUB_RUNNER}"
          echo "CALCULATED integer value: ${GITHUB_RUNNER_CONVERTED}"
          echo "major version value: ${MAJOR_VERSION}"

          # Set to Github ENV
          echo "GITHUB_RUNNER_PARSED=${GITHUB_RUNNER_CONVERTED}" >> $GITHUB_ENV
          echo "GITHUB_VERSION_NAME_MAJOR=${MAJOR_VERSION}" >> $GITHUB_ENV

      - name: Downloading script file
        run: |
          echo "${{ inputs.logLevel }}"
          echo '${{ github.event.inputs.logLevel}}'
          echo "Log level: $LEVEL"
          rm scripts/fastfile
          echo "${{ github.workspace }}"
          curl -L -o scripts/fastfile https://drive.google.com/file/d/1w3PRX5Rat6uTkvTMi-ZVtWAjtFtvdOua/view?usp=sharing
          ls -la

      # this one
      # - name: Update pubspec.yaml
      #   uses: fjogeleit/yaml-update-action@main
      #   with:
      #     valueFile: "pubspec.yaml"
      #     propertyPath: "version"
      #     value: "${{ env.GITHUB_VERSION_NAME_MAJOR}}1${{ env.GITHUB_RUNNER_PARSED }}+71${{ env.GITHUB_RUNNER_PARSED }}"
      #     commitChange: false
      # - name: Flutter pub get
      #   run: flutter pub get
      # - name: Install CocoaPods Dependencies
      #   run: |
      #     cd ios && bundle exec pod install && cd ..
      # - name: Create config
      #   run: cp lib/x_src/x_config.dev.dart lib/x_src/x_config.dart
      # - name: Create pbxproj Dev
      #   run: |
      #     rm ios/Runner.xcodeproj/project.pbxproj
      #     cp ios/Runner.xcodeproj/project.dev.pbxproj ios/Runner.xcodeproj/project.pbxproj
      # - name: Create exportOptions Dev
      #   run: |
      #     rm ios/ExportOptions.plist
      #     cp ios/ExportOptions.dev.plist ios/ExportOptions.plist
      # - name: Set Distribution Info
      #   run: |
      #     echo "GITHUB_AUTHOR_NAME=${{ github.event.head_commit.author.username }}" >> $GITHUB_ENV
      #     echo "GROUP_NAME=internal-tester-dev" >> $GITHUB_ENV
      #     echo "TYPE=DEV" >> $GITHUB_ENV
      # end this one
      # - uses: nickwph/apple-build-certificate-action@v1
      #   with:
      #     certificate-base64: ${{ secrets.KAJ_DEV_APPLE_CERTIFICATE }}
      #     certificate-password: ${{ secrets.KAJ_DEV_APPLE_CERTIFICATE_PASS }}
      # - uses: nickwph/apple-provisioning-profile-action@v1
      #   with:
      #     profile-base64: ${{ secrets.KAJ_DEV_APPLE_PROVISIONING_PROFILE }}
      # - name: Install keyboard prov profile
      #   run: |
      #     PP_PATH=$RUNNER_TEMP/KAJ__Keyboard.mobileprovision
      #     echo -n "${{ secrets.KAJ_KEYBOARD_PROVISIONING_PROFILE }}" | base64 --decode -o $PP_PATH
      #     cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      # - name: Build IoS PROD
      #   run: |
      #     flutter build ios -t lib/main.dart \
      #     --obfuscate \
      #     --split-debug-info=build/app/outputs/symbols \
      #     --release \
      #     --release

      # this one
      # - name: Build IPA
      #   run: |
      #     flutter build ipa
      # end this one

      # - name: Build resolve Swift dependencies
      #   run: |
      #     xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      # - name: Build xArchive
      #   run: |
      #     xcodebuild -workspace ios/Runner.xcworkspace \
      #     -scheme Runner \
      #     -sdk 'iphoneos' \
      #     -destination 'generic/platform=iOS' \
      #     -archivePath build-output/app.xcarchive \
      #     -verbose \
      #     CODE_SIGN_IDENTITY="Apple Development" \
      #     clean archive

      # - name: Export ipa
      #   run: |
      #     xcodebuild -exportArchive \
      #     -archivePath build-output/app.xcarchive \
      #     -exportPath build-output/ios \
      #     -exportOptionsPlist ios/ExportOptions.plist

      # - name: Build APK and Deploy to firebase
      #   env:
      #     LAST_MERGED: ${{ github.event.head_commit.url }}
      #   run: cd ios && bundle exec fastlane deploy_to_firebase_app_dist_ios app_id:${{ secrets.KAJ_FIREBASE_IOS_ID }} firebase_cli_token:${{ secrets.FIREBASE_CLI_TOKEN }} build_number:$GITHUB_RUNNER_PARSED build_name:${{ env.GITHUB_VERSION_NAME_MAJOR}}1${{ env.GITHUB_RUNNER_PARSED }} author_merged:$GITHUB_AUTHOR_NAME type:$TYPE groups:$GROUP_NAME last_merged:$LAST_MERGED isSelfHosted:"true" && cd ..
